### ISSUE TITLE
CloudV online EDA tool is pending on connecting status

### ISSUE THREAD

**Issue by Waxpple** [Cloud-V/Issues#35]
CloudV online EDA tool is pending on connecting status.
Can do validation but cannot do synthesis.

BR,
Ethan

**Comment by donn** [comment]
Yeah I'm still working out some fixes. This website inches on more effort than its worth sometimes...

Which SCL are you using?

**Comment by Waxpple** [comment]
I want to use the skywater 130A.
Thanks! Looking forward to trying it out.

BR,
Ethan

**Comment by donn** [comment]
I'll tell you when I've got a fix!

**Comment by donn** [comment]
Well, that took forever. But it's fixed now!

**Comment by Waxpple** [comment]
> Well, that took forever. But it's fixed now!

Thanks!
