### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by MagdElDinAhmed** [Cloud-V/Issues#38]
ERR_NETWORK_ACCESS_DENIED is what shows up
When I try my phone, it gives me ERR_CONNECTION_REFUSED
This issue occurs on different networks (I used AUC-WLAN and my mobile hotspot), and on different browsers (A fork of Firefox called LibreWolf and a fork of Chromium called Brave)

**Comment by donn** [comment]
Turned out to be a DNS issue. Sorry for the inconvenience.
