### ISSUE TITLE
[UI/UX] Tabs fail to close on Mozilla Firefox

### ISSUE THREAD

**Issue by donn** [Cloud-V/Issues#9]
Tabs fail to close on Mozilla Firefox 55.0.2 (64-bit), Ubuntu.

**Comment by ash0x0** [comment]
Works fine on both 55.0.2 and 57.0b3 (64-bit), Ubuntu. What do you mean by fail to close?

**Comment by ash0x0** [comment]
They do fail to display correctly, need to fix width. Otherwise no issues. Reproduce.

**Comment by donn** [comment]
Issue has been fixed. Welp. You can thank Agiza for being so secretive.
